### ISSUE TITLE
Issue/change facebooksdk

### ISSUE THREAD

**Issue by wubuyun** [facebookincubator/wordpress-messenger-customer-chat-plugin#1]
Link removed
          js.src = "https://connect.facebook.net/<?php echo $locale; ?>/sdk.js";
To
          js.src = "https://connect.facebook.net/<?php echo $locale; ?>/sdk/xfbml.customerchat.js";

**Comment by bhayani** [comment]
Updated in 0512c528fa3c6688624ac06dc91d0ce36b0d5263
