### ISSUE TITLE
Not appearing in Safari web browser

### ISSUE THREAD

**Issue by coolwebs** [facebookincubator/wordpress-messenger-customer-chat-plugin#2]
Is there any specific reason why the Facebook Messenger icon nor chat window appears when using the Safari Web Browser? I've checked and seen it works on both Chrome and Firefox. I followed the recommended steps also in the instruction file too.

**Comment by bhayani** [comment]
@coolwebs - We had an issue with Safari so we had disabled it. The issue has been resolved. Please let us know if the Customer Chat Plugin is not working for Safari.
