### ISSUE TITLE
Enhancement: Add X button to close the chat window

### ISSUE THREAD

**Issue by k3nsai** [facebookincubator/wordpress-messenger-customer-chat-plugin#3]
As it is not obvious and it can be confusing for users that suddenly see a window popup without an option to close it:

Can we please have an X on the top right corner of the chat window, so we can close the window at any time without having to click the "thunder" icon that opens the chat in the first place?

**Comment by bhayani** [comment]
Thanks for the feedback. The customer chat plugin now has an X so you can close it.
